services:
  - type: web
    name: eval-app-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false        # paste your Atlas URI in Render dashboard
      - key: PORT
        value: 5000
